# Generated by Django 3.0.7 on 2020-07-06 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200705_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='follows',
            new_name='followed_users',
        ),
    ]
