# Generated by Django 3.0.7 on 2020-07-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20200701_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='message',
            new_name='inner_message',
        ),
        migrations.AddField(
            model_name='card',
            name='outer_message',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
