# Generated by Django 3.0.7 on 2020-07-01 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20200701_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='message',
            new_name='outer_message',
        ),
    ]
