# Generated by Django 3.0.7 on 2020-07-01 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auto_20200701_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='inner_message',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='card',
            name='outer_message',
        ),
    ]
