# Generated by Django 3.0.7 on 2020-07-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_auto_20200701_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='message',
            new_name='inner_message',
        ),
        migrations.AddField(
            model_name='card',
            name='outer_message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
