# Generated by Django 3.0.7 on 2020-07-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_auto_20200701_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='border',
            field=models.CharField(choices=[('None', 'None'), ('Solid', 'Solid'), ('Inset', 'Inset')], default='None', max_length=500),
        ),
    ]
