# Generated by Django 3.0.7 on 2020-07-02 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0017_userfollowing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollowing',
        ),
    ]
