# Generated by Django 3.0.7 on 2020-07-02 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0019_follower'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
