# Generated by Django 3.0.7 on 2020-07-02 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0021_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
