# Generated by Django 3.0.7 on 2020-07-02 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0022_delete_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='user',
            new_name='author',
        ),
    ]
