# Generated by Django 3.0.7 on 2020-07-02 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0023_auto_20200702_2228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['-posted_at']},
        ),
    ]
